# Site settings
title: Lawrence Aberba
description:
    "I design and code. Full stack engineer (UIX, React + Node.Js, D, PWAs,
    SaaS, Payments, Dashboards, Landing Pages, ...). Open Source contributor.
    Simplicity. Modern Web. Passionate about SaaS."
url: "/"
baseurl: ""
google_analytics: "UA-125100053-1"
disqus_shortname: "laberba"

author:
    name: "Lawrence Aberba"
    email: karabutaworld@gmail.com
    twitter_username: aberbamx
    facebook_username: aberba.lawrence
    github_username: aberba
    linkedin_username: lawrence-aberba-a2b65a143

plugins:
    - jekyll-paginate

defaults:
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"

# Build settings
destination: _site
paginate: 10
permalink: :year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
    # use Github Flavored Markdown
    input: GFM
    # do not replace newlines by <br>s
    hard_wrap: false

gems: ["jekyll-paginate"]
exclude: ["README.md", "Gemfile", "Gemfile.lock", "screenshot.png"]
